spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  sql:
    init:
      mode: never



idam:
  api:
    url: ${IDAM_API_URL:http://localhost:8891}

logging:
  level:
    uk.gov.hmcts.reform: DEBUG

pact:
  idam:
    redirect_uri: http://www.dummy-pact-service.com/callback
    grant_type: password
    client_id: laupact
    client_secret: pactsecret
    username: lau-pact-user@hmcts.net
    password: Password123
    scope: openid profile roles
