server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Idam Log and Audit
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LAU_IDAM_DB_HOST:localhost}:${LAU_IDAM_DB_PORT:5432}/${LAU_IDAM_DB_NAME:lau_idam}${LAU_IDAM_DB_CONN_OPTIONS:}
    username: ${LAU_IDAM_DB_USERNAME:lauuser}
    password: ${LAU_IDAM_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 20
      idleTimeout: 10000
      poolName: LAUIdamHikariCP
      maxLifetime: 7200000
      connectionTimeout: 60000
  #    tomcat:
  #      max-active: 10
  #      max-idle: 10
  #      min-idle: 2
  #      max-wait: 10000
  #      test-on-borrow: true
  #      test-on-connect: true
  #      test-on-idle: true
  #      validation-query: "SELECT 1"
  #      time-between-eviction-runs-millis: 10000
  #      test-while-idle: true
  #      test-on-return: true
  #      remove-abandoned: true
  #      remove-abandoned-timeout: 60
  #      log-abandoned: true
  #      abandon-when-percentage-full: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
  flyway:
    enabled: ${LAU_FLYWAY_MIGRATE_DB:false}
    user: ${LAU_IDAM_DB_ADMIN_USERNAME:}
    password: ${LAU_IDAM_DB_ADMIN_PASSWORD:}
    placeholders:
      LAU_IDAM_DB_PASSWORD: ${LAU_IDAM_DB_PASSWORD:}

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4502}

authorised.services: idam-web-admin,lau-idam-frontend

azure:
  application-insights:
    instrumentation-key: ${lau.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

flyway:
  noop:
    strategy: "false"

