server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#Application specific properties
api-error-messages:
  bad_request: Invalid Request
  created: Successfully created
  accepted: Success
  internal_error: Unknown error occurred
api-required-header-keys:
  co-relationid: X-Correlation-Id
api-schema-file:
  submitanswer-schema: JsonSchema/submitAnswersSchema.json
api-version-number: 1

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: LAU Idam Backend
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:10://localhost/lau-idam
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    placeholders:
      LAU_IDAM_DB_PASSWORD: laupass

flyway:
  noop:
    strategy: "false"

security:
  db:
    backend-encryption-key: ${LAU_IDAM_ENCRYPTION_KEY:ThisIsATestKeyForEncryption}

idam:
  s2s-auth:
    url: http://localhost:4554
    secret-cs: AAAAAAAAAAAAAAAA
    name-cs: ccd_data,lau_frontend
  api:
    url: http://localhost:4554
  client:
    id: lau
    secret: 12345678
    redirect_uri: http://localhost:3451/oauth2redirect

authorised.services: idam-web-admin,lau_frontend
authorised.roles: cft-audit-investigator

targetInstance: ${TEST_URL:http://localhost:4550}
