java:
  environment:
    LAU_IDAM_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
    LAU_IDAM_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    LAU_IDAM_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    LAU_IDAM_DB_ADMIN_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
    LAU_IDAM_DB_ADMIN_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    LAU_IDAM_DB_HOST: "{{ .Release.Name }}-postgresql"
    LAU_IDAM_DB_PORT: "5432"
    FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}"
    FLYWAY_USER: "{{ .Values.postgresql.postgresqlUsername }}"
    FLYWAY_PASSWORD: "{{ .Values.postgresql.postgresqlPassword }}"
    FLYWAY_NOOP_STRATEGY: "false"
    LAU_IDAM_DB_CONN_OPTIONS: "?sslmode=allow"
    LAU_IDAM_ENCRYPTION_ENABLED: "No"
    TEST_S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    TEST_IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
    TEST_IDAM_CLIENT_REDIRECT_URI: "https://lau-idam-backend-aat.service.core-compute-aat.internal/oauth2/callback"
    TEST_IDAM_CLIENT_NAME: 'lau'
    LAU_FLYWAY_MIGRATE_DB: "true"
    DB_ALLOW_DELETE_RECORD: "true"
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  postgresql:
    enabled: true
    postgresqlUsername: lauadmin
    postgresqlPassword: laupass
    postgresqlDatabase: lau_idam
    initdbUser: postgres
    initdbScripts:
      init.sql: |-
        CREATE ROLE lauuser WITH LOGIN PASSWORD 'laupass';
        CREATE EXTENSION IF NOT EXISTS pgcrypto;
