# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  environment:
    DB_ALLOW_DELETE_RECORD: "true"
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
